apiVersion: v1
kind: Pod
metadata:
  name: tinyserver1
labels:
  app: tinyserver
spec:
  nodeName: "node1"
  containers:
    - name: server
      image: chasingdreams/tinyweb:2
      ports:
        - name: http
          containerPort: 80
      volumeMounts:
        - name: volume04
          mountPath: /usr/share/nginx/html
  volumes:
    - name: volume04
      hostPath: /home/webs/web0
