apiVersion: v1
kind: Pod
metadata:
  name: tinyserver1
  labels:
    app: tinyserver
spec:
  nodeName: "node1"
  containers:
    - name: server
      image: chasingdreams/tinyweb:3
      ports:
        - name: http
          containerPort: 80

