apiVersion: v1
kind: Pod
metadata:
  name: tinyserver3
  labels:
    app: tinyserver
spec:
  nodeName: "node1"
  containers:
    - name: server
      image: chasingdreams/tinyweb:2
      ports:
        - name: http
          containerPort: 80
      volumeMounts:
        - name: volume06
          mountPath: /usr/share/nginx/html
  volumes:
    - name: volume06
      hostPath: /home/webs/web2
