stages:
  - build
  - test

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - /bin/

build:
  stage: build
  only:
    - apiserver
  script:
    - echo "CloudOS_g15_1" | sudo -S /usr/local/go/bin/go build -o /bin/apiserver ./cmd/kube-apiserver/kube-apiserver.go
  tags:
    - testing


test:
  stage: test
  only:
    - apiserver
  script:
    - echo "CloudOS_g15_1" | sudo -S /usr/local/go/bin/go test ./cmd/kube-apiserver/test/etcd_test.go
    # - go test ./...
  tags:
    - testing

