stages:
  - build
  - test

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - /test/bin/

build:
  stage: build
  only:
    - apiserver
  script:
    - go build -o /test/bin/apiserver ./cmd/kube-apiserver/kube-apiserver.go
  tags:
    - testing

test:
  stage: test
  only:
    - apiserver
  script:
    - ./test/bin/apiserver
  tags:
    - testing

