stages:
  - build
  - test

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - /bin/

build:
  stage: build
  only:
    - apiserver
  script:
    - go build -o /bin/apiserver ./cmd/kube-apiserver/kube-apiserver.go
  tags:
    - test_docker

test:
  stage: test
  only:
    - apiserver
  script:
    - ./bin/apiserver
  tags:
    - test_docker

