stages:
  - build
  - test

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - /bin/

build:
  stage: build
  script:
    - sudo /usr/local/go/bin/go build -o /bin/kube-apiserver ./cmd/kube-apiserver/kube-apiserver.go
    - sudo /usr/local/go/bin/go build -o /bin/kube-scheduler ./cmd/kube-scheduler/kube-scheduler.go
    - sudo /usr/local/go/bin/go build -o /bin/kubelet ./cmd/kubelet/kubelet.go
    - sudo /usr/local/go/bin/go build -o /bin/kube-controller-manager ./cmd/kube-controller-manager/kube-controller-manager.go
    - sudo /usr/local/go/bin/go build -o /bin/kubeservice ./cmd/kube-service/kubeservice.go
    - sudo /usr/local/go/bin/go build -o /bin/kubeproxy ./cmd/kube-proxy/kubeproxy.go
  tags:
    - testing


test:
  stage: test
  script:
    - make stop
    - make clean
    - sudo make build
    - sudo make run
    - sudo /usr/local/go/bin/go test ./... -v
    - make stop
    - make clean
  tags:
    - testing
