stages:
  - build
  - test

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - /bin/

build:
  stage: build
  only:
    - apiserver,gpu
  script:
    - sudo /usr/local/go/bin/go build -o /bin/apiserver ./cmd/kube-apiserver/kube-apiserver.go
    - sudo /usr/local/go/bin/go build -o /bin/apiserver ./cmd/kube-controller/job-controller.go
  tags:
    - testing


test:
  stage: test
  only:
    - apiserver,gpu
  script:
    - sudo /usr/local/go/bin/go test ./...
  tags:
    - testing

