apiVersion: v1
kind: Pod
metadata:
  name: res
  labels:
    app: res
spec:
  containers:
    - name: server
      image: chasingdreams/tinyweb:3
      ports:
        - name: http
          containerPort: 80
      limitResource:
        memory: 50M
        cpu: 1


