apiVersion: v1
kind: Pod
metadata:
  name: nginxtest
spec:
  nodeName: "node1"
  containers:
    - name: nginx
      image: nginx
      ports:
        - name: http
          containerPort: 80
      volumeMounts:
        - name: volume-nginx
          mountPath: /etc/nginx
  volumes:
    - name: volume-nginx
      hostPath: /root/nginx