apiVersion: v1
kind: Pod
metadata:
  name: test5
spec:
  nodeName: "node1"
  containers:
    - name: my-container
      image: nginx:latest
      command: ["nginx", "-g", "daemon off;"]
      resources:
        limits:
          cpu: "1"
          memory: "128Mi"
      ports:
        - containerPort: 80
      volumeMounts:
        - name: my-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: my-volume
      configMap:
        name: my-configmap