apiVersion: v1
kind: Pod
metadata:
  name: test5
  labels:
    app: my-app
spec:
  nodeName: "node1"
  containers:
    - name: my-container
      image: chasingdreams/tinyweb:3
      command: ["/bin/sh", "-c", "timeout 120s sh -c 'while true; do :; done' ; sleep 30"]
      ports:
        - containerPort: 80
  volumes:
    - name: my-volume
      configMap:
        name: my-configmap
