apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: chasingdreams/tinyweb:30sfail
#          command: ["timeout", "30s", "/bin/sh", "-c", "while true; do :; done"]
          resources:
            limits:
              cpu: "1"
              memory: "128Mi"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: my-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: my-volume
          configMap:
            name: my-configmap