apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: cpu_stress_container
          image: busybox
#          entryPoint: ["/bin/sh"]
          command: ["timeout", "300s", "/bin/sh", "-c", "while true; do :; done"]
          limitResource:
            cpu: "1"
            memory: "128Mi"