apiVersion: v1
kind: Pod
metadata:
  name: tinyserver
spec:
  labels:
    app: tinyserver
  nodeName: "node1"
  containers:
    - name: server
      image: chasingdreams/tinyweb:2
      ports:
        - name: http
          containerPort: 80
