apiVersion: v1
kind: Service
metadata:
  name: webservice
spec:
  name: webservice
  clusterIP: "11.1.1.1"
  selector:
    app: "tinyserver"
  ports:
    - port: "80"
      protocol: tcp
      targetPort: "80"

