apiVersion: v1
kind: Pod
metadata:
  name: sche-pod-5
  labels:
    app: sche-pod-5
spec:
  containers:
    - name: server
      image: chasingdreams/tinyweb:3
      ports:
        - name: http
          containerPort: 80

