build:
  stage: build
  only:
    - apiserver
  script:
    - go build -o bin/apiserver ../cmd/kube-apiserver/kube-apiserver.go
  tags:
    - test

test:
  stage: test
  only:
    - apiserver
  script:
    - ./bin/kube-apiserver
    -  go test ../cmd/kube-apiserver/test/etcd_test.go
  tags:
    - test