apiVersion: v1
kind: Pod
metadata:
  name: dns-example-pod1
  labels:
    app: dns-example-pod1
spec:
  containers:
    - name: server
      image: chasingdreams/tinyweb:3
      ports:
        - name: http
          containerPort: 80

