apiVersion: v1
kind: Pod
metadata:
  name: user1
  labels:
    app: user1
spec:
  nodeName: "node1"
  containers:
    - name: server
      image: chasingdreams/minor_ubuntu:v3
      tty: true
      command: ["/bin/sh"]

